// Catálogo curado de produtos por categoria, cobrindo do básico ao topo de linha.
// Usado na comparação por lista clicável (/catalogo).
// A 1ª spec é a faixa (Entrada / Custo-benefício / Intermediária / Alto desempenho / Topo de linha).
// Para crescer: basta adicionar itens nas listas abaixo.

export interface CatalogItem {
  /** Nome exato do produto (usado na comparação por IA). */
  name: string;
  /** Specs curtas para o card. A 1ª é a faixa de preço/posicionamento. */
  specs: string[];
}

export interface CatalogCategory {
  id: string;
  label: string;
  icon: string;
  items: CatalogItem[];
}

export const CATALOG: CatalogCategory[] = [
  {
    id: "gpu",
    label: "Placas de Vídeo",
    icon: "🎮",
    items: [
      { name: "NVIDIA GeForce RTX 5090", specs: ["Topo de linha", "32 GB GDDR7"] },
      { name: "NVIDIA GeForce RTX 5080", specs: ["Topo de linha", "16 GB GDDR7"] },
      { name: "NVIDIA GeForce RTX 4090", specs: ["Topo de linha", "24 GB GDDR6X"] },
      { name: "AMD Radeon RX 7900 XTX", specs: ["Topo de linha", "24 GB GDDR6"] },
      { name: "NVIDIA GeForce RTX 5070 Ti", specs: ["Alto desempenho", "16 GB GDDR7"] },
      { name: "NVIDIA GeForce RTX 4080 Super", specs: ["Alto desempenho", "16 GB GDDR6X"] },
      { name: "AMD Radeon RX 7900 XT", specs: ["Alto desempenho", "20 GB GDDR6"] },
      { name: "AMD Radeon RX 9070 XT", specs: ["Alto desempenho", "16 GB GDDR6"] },
      { name: "NVIDIA GeForce RTX 5070", specs: ["Alto desempenho", "12 GB GDDR7"] },
      { name: "NVIDIA GeForce RTX 4070 Ti Super", specs: ["Alto desempenho", "16 GB GDDR6X"] },
      { name: "NVIDIA GeForce RTX 4070 Super", specs: ["Alto desempenho", "12 GB GDDR6X"] },
      { name: "AMD Radeon RX 7800 XT", specs: ["Alto desempenho", "16 GB GDDR6"] },
      { name: "NVIDIA GeForce RTX 4070", specs: ["Intermediária", "12 GB GDDR6X"] },
      { name: "AMD Radeon RX 7700 XT", specs: ["Intermediária", "12 GB GDDR6"] },
      { name: "NVIDIA GeForce RTX 3070", specs: ["Intermediária", "8 GB GDDR6"] },
      { name: "NVIDIA GeForce RTX 4060 Ti", specs: ["Intermediária", "8 GB GDDR6"] },
      { name: "AMD Radeon RX 6750 XT", specs: ["Intermediária", "12 GB GDDR6"] },
      { name: "NVIDIA GeForce RTX 4060", specs: ["Custo-benefício", "8 GB GDDR6"] },
      { name: "AMD Radeon RX 7600", specs: ["Custo-benefício", "8 GB GDDR6"] },
      { name: "NVIDIA GeForce RTX 3060", specs: ["Custo-benefício", "12 GB GDDR6"] },
      { name: "AMD Radeon RX 6650 XT", specs: ["Custo-benefício", "8 GB GDDR6"] },
      { name: "Intel Arc A750", specs: ["Custo-benefício", "8 GB GDDR6"] },
      { name: "NVIDIA GeForce RTX 3050", specs: ["Entrada", "8 GB GDDR6"] },
      { name: "NVIDIA GeForce GTX 1660 Super", specs: ["Entrada", "6 GB GDDR6"] },
      { name: "AMD Radeon RX 6600", specs: ["Entrada", "8 GB GDDR6"] },
      { name: "NVIDIA GeForce GTX 1650", specs: ["Entrada", "4 GB GDDR6"] },
      { name: "AMD Radeon RX 6500 XT", specs: ["Entrada", "4 GB GDDR6"] },
      { name: "Intel Arc A380", specs: ["Entrada", "6 GB GDDR6"] },
      { name: "NVIDIA GeForce GT 1030", specs: ["Básica", "2 GB"] },
      { name: "AMD Radeon RX 9070", specs: ["Alto desempenho", "16 GB GDDR6"] },
      { name: "AMD Radeon RX 7900 GRE", specs: ["Alto desempenho", "16 GB GDDR6"] },
      { name: "NVIDIA GeForce RTX 5060 Ti", specs: ["Intermediária", "16 GB GDDR7"] },
      { name: "NVIDIA GeForce RTX 5060", specs: ["Custo-benefício", "8 GB GDDR7"] },
      { name: "AMD Radeon RX 9060 XT", specs: ["Custo-benefício", "16 GB GDDR6"] },
      { name: "Intel Arc B580", specs: ["Custo-benefício", "12 GB GDDR6"] },
    ],
  },
  {
    id: "cpu",
    label: "Processadores",
    icon: "⚙️",
    items: [
      { name: "AMD Ryzen 9 9950X", specs: ["Topo de linha", "16 núcleos", "AM5"] },
      { name: "AMD Ryzen 9 7950X3D", specs: ["Topo de linha", "16 núcleos", "AM5"] },
      { name: "Intel Core i9-14900K", specs: ["Topo de linha", "24 núcleos"] },
      { name: "Intel Core Ultra 9 285K", specs: ["Topo de linha", "24 núcleos"] },
      { name: "AMD Ryzen 7 9800X3D", specs: ["Alto desempenho", "8 núcleos", "AM5"] },
      { name: "AMD Ryzen 7 7800X3D", specs: ["Alto desempenho", "8 núcleos", "AM5"] },
      { name: "Intel Core i7-14700K", specs: ["Alto desempenho", "20 núcleos"] },
      { name: "AMD Ryzen 7 5800X3D", specs: ["Alto desempenho", "8 núcleos", "AM4"] },
      { name: "Intel Core i7-13700K", specs: ["Alto desempenho", "16 núcleos"] },
      { name: "Intel Core i5-14600K", specs: ["Intermediária", "14 núcleos"] },
      { name: "AMD Ryzen 7 7700", specs: ["Intermediária", "8 núcleos", "AM5"] },
      { name: "AMD Ryzen 5 7600", specs: ["Intermediária", "6 núcleos", "AM5"] },
      { name: "Intel Core i5-13400F", specs: ["Intermediária", "10 núcleos"] },
      { name: "AMD Ryzen 7 5700X", specs: ["Custo-benefício", "8 núcleos", "AM4"] },
      { name: "AMD Ryzen 5 5600", specs: ["Custo-benefício", "6 núcleos", "AM4"] },
      { name: "AMD Ryzen 5 5600G", specs: ["Custo-benefício", "vídeo integrado"] },
      { name: "Intel Core i5-12400F", specs: ["Custo-benefício", "6 núcleos"] },
      { name: "Intel Core i3-12100F", specs: ["Entrada", "4 núcleos"] },
      { name: "AMD Ryzen 5 4500", specs: ["Entrada", "6 núcleos", "AM4"] },
      { name: "AMD Ryzen 3 4100", specs: ["Entrada", "4 núcleos", "AM4"] },
      { name: "AMD Athlon 3000G", specs: ["Básica", "vídeo integrado"] },
      { name: "Intel Pentium Gold G6400", specs: ["Básica", "2 núcleos"] },
      { name: "AMD Ryzen 9 9900X", specs: ["Topo de linha", "12 núcleos", "AM5"] },
      { name: "Intel Core Ultra 7 265K", specs: ["Alto desempenho", "20 núcleos"] },
      { name: "AMD Ryzen 7 9700X", specs: ["Alto desempenho", "8 núcleos", "AM5"] },
      { name: "Intel Core Ultra 5 245K", specs: ["Intermediária", "14 núcleos"] },
      { name: "AMD Ryzen 5 9600X", specs: ["Intermediária", "6 núcleos", "AM5"] },
      { name: "AMD Ryzen 5 8600G", specs: ["Custo-benefício", "vídeo integrado", "AM5"] },
      { name: "Intel Core i5-14400F", specs: ["Custo-benefício", "10 núcleos"] },
    ],
  },
  {
    id: "ssd",
    label: "SSDs",
    icon: "💾",
    items: [
      { name: "Crucial T705 2TB", specs: ["Topo de linha", "Gen5", "14500 MB/s"] },
      { name: "Samsung 990 Pro 2TB", specs: ["Alto desempenho", "Gen4", "7450 MB/s"] },
      { name: "WD Black SN850X 2TB", specs: ["Alto desempenho", "Gen4", "7300 MB/s"] },
      { name: "Kingston KC3000 1TB", specs: ["Alto desempenho", "Gen4", "7000 MB/s"] },
      { name: "Seagate FireCuda 530 2TB", specs: ["Alto desempenho", "Gen4"] },
      { name: "Samsung 980 Pro 1TB", specs: ["Intermediária", "Gen4", "7000 MB/s"] },
      { name: "WD Black SN770 1TB", specs: ["Intermediária", "Gen4", "5150 MB/s"] },
      { name: "Crucial P3 Plus 1TB", specs: ["Custo-benefício", "Gen4", "5000 MB/s"] },
      { name: "WD Blue SN580 1TB", specs: ["Custo-benefício", "Gen4", "4150 MB/s"] },
      { name: "Kingston NV2 1TB", specs: ["Custo-benefício", "Gen4", "3500 MB/s"] },
      { name: "Crucial P3 500GB", specs: ["Entrada", "Gen3"] },
      { name: "Samsung 870 EVO 1TB", specs: ["Entrada", "SATA", "560 MB/s"] },
      { name: "Kingston A400 480GB", specs: ["Entrada", "SATA", "500 MB/s"] },
      { name: "Crucial BX500 480GB", specs: ["Básica", "SATA"] },
      { name: "Kingston KC3000 2TB", specs: ["Topo de linha", "Gen4", "7000 MB/s"] },
      { name: "Crucial T500 1TB", specs: ["Alto desempenho", "Gen4", "7400 MB/s"] },
      { name: "Samsung 990 Pro 1TB", specs: ["Alto desempenho", "Gen4", "7450 MB/s"] },
      { name: "Kingston NV3 2TB", specs: ["Custo-benefício", "Gen4", "6000 MB/s"] },
      { name: "Samsung 980 1TB", specs: ["Custo-benefício", "Gen3", "3500 MB/s"] },
    ],
  },
  {
    id: "notebook",
    label: "Notebooks",
    icon: "💻",
    items: [
      { name: "Apple MacBook Pro 16 M3 Max", specs: ["Topo de linha", "M3 Max"] },
      { name: "Asus ROG Strix Scar 18", specs: ["Topo (gamer)", "RTX 4090"] },
      { name: "Dell Alienware m16", specs: ["Alto desempenho", "gamer"] },
      { name: "Asus ROG Zephyrus G16", specs: ["Alto desempenho", "RTX 4070/4080"] },
      { name: "Lenovo Legion Pro 5", specs: ["Alto desempenho", "RTX 4070"] },
      { name: "Apple MacBook Pro 14 M3 Pro", specs: ["Alto desempenho", "M3 Pro"] },
      { name: "Dell XPS 15", specs: ["Alto desempenho", "Core i7/i9"] },
      { name: "Asus ROG Zephyrus G14", specs: ["Alto desempenho", "RTX 4060"] },
      { name: "Apple MacBook Air M3", specs: ["Intermediária", "M3", "leve"] },
      { name: "Lenovo LOQ", specs: ["Intermediária (gamer)", "RTX 4050/4060"] },
      { name: "Samsung Galaxy Book4", specs: ["Intermediária", "Core i5/i7"] },
      { name: "Acer Nitro 5", specs: ["Custo-benefício (gamer)", "RTX 4050"] },
      { name: "Dell G15", specs: ["Custo-benefício (gamer)", "RTX 4050"] },
      { name: "Asus TUF Gaming F15", specs: ["Custo-benefício (gamer)", "RTX 4060"] },
      { name: "Asus Vivobook 15", specs: ["Custo-benefício", "uso geral"] },
      { name: "Acer Aspire 5", specs: ["Custo-benefício", "uso geral"] },
      { name: "Lenovo IdeaPad Slim 3", specs: ["Entrada", "uso geral"] },
      { name: "Dell Inspiron 15", specs: ["Entrada", "uso geral"] },
      { name: "Acer Aspire 3", specs: ["Entrada", "uso geral"] },
      { name: "Positivo Motion", specs: ["Básico", "tarefas leves"] },
      { name: "Apple MacBook Pro 14 M4 Pro", specs: ["Alto desempenho", "M4 Pro"] },
      { name: "Asus ROG Strix G16", specs: ["Alto desempenho (gamer)", "RTX 4070"] },
      { name: "Acer Predator Helios Neo 16", specs: ["Alto desempenho (gamer)", "RTX 4060/4070"] },
      { name: "Lenovo Legion Slim 5", specs: ["Intermediária (gamer)", "RTX 4060"] },
    ],
  },
  {
    id: "ram",
    label: "Memórias RAM",
    icon: "🧠",
    items: [
      { name: "G.Skill Trident Z5 64GB DDR5 6000MHz", specs: ["Topo de linha", "DDR5", "2x32GB"] },
      { name: "Corsair Dominator 32GB DDR5 6400MHz", specs: ["Alto desempenho", "DDR5"] },
      { name: "G.Skill Trident Z5 32GB DDR5 6000MHz CL30", specs: ["Alto desempenho", "DDR5"] },
      { name: "Corsair Vengeance 32GB DDR5 6000MHz", specs: ["Intermediária", "DDR5", "2x16GB"] },
      { name: "Kingston Fury Beast 32GB DDR5 6000MHz", specs: ["Intermediária", "DDR5"] },
      { name: "Corsair Vengeance 16GB DDR5 5200MHz", specs: ["Custo-benefício", "DDR5"] },
      { name: "Kingston Fury Beast 16GB DDR4 3600MHz", specs: ["Custo-benefício", "DDR4"] },
      { name: "Corsair Vengeance LPX 16GB DDR4 3200MHz", specs: ["Custo-benefício", "DDR4", "2x8GB"] },
      { name: "Kingston Fury 8GB DDR4 3200MHz", specs: ["Entrada", "DDR4"] },
      { name: "Memória 8GB DDR4 2666MHz", specs: ["Básica", "DDR4"] },
      { name: "Corsair Vengeance RGB 32GB DDR5 6000MHz", specs: ["Alto desempenho", "DDR5", "CL30"] },
      { name: "G.Skill Ripjaws S5 32GB DDR5 6000MHz", specs: ["Alto desempenho", "DDR5", "CL30"] },
      { name: "Corsair Vengeance 32GB DDR5 6400MHz", specs: ["Alto desempenho", "DDR5"] },
      { name: "Kingston Fury Beast 16GB DDR5 5600MHz", specs: ["Custo-benefício", "DDR5"] },
    ],
  },
  {
    id: "motherboard",
    label: "Placas-mãe",
    icon: "🧩",
    items: [
      { name: "ASUS ROG Crosshair X870E Hero", specs: ["Topo de linha", "AM5", "X870E"] },
      { name: "MSI MEG Z790 ACE", specs: ["Topo de linha", "LGA1700", "Z790"] },
      { name: "ASUS ROG Strix X670E-E Gaming", specs: ["Alto desempenho", "AM5", "X670E"] },
      { name: "Gigabyte X670 Aorus Elite AX", specs: ["Alto desempenho", "AM5"] },
      { name: "MSI MAG B650 Tomahawk WiFi", specs: ["Intermediária", "AM5", "B650"] },
      { name: "ASUS TUF Gaming B650-Plus", specs: ["Intermediária", "AM5"] },
      { name: "MSI MAG B760 Tomahawk WiFi", specs: ["Intermediária", "LGA1700", "B760"] },
      { name: "Gigabyte B650M DS3H", specs: ["Custo-benefício", "AM5", "mATX"] },
      { name: "ASUS Prime B650M-A", specs: ["Custo-benefício", "AM5"] },
      { name: "MSI PRO B760M-A WiFi", specs: ["Custo-benefício", "LGA1700"] },
      { name: "ASRock B550M Steel Legend", specs: ["Custo-benefício", "AM4", "B550"] },
      { name: "Gigabyte B450M DS3H", specs: ["Entrada", "AM4", "B450"] },
      { name: "ASUS Prime A520M-K", specs: ["Entrada", "AM4"] },
      { name: "Gigabyte H610M H", specs: ["Entrada", "LGA1700", "H610"] },
      { name: "ASUS ROG Strix B650E-F Gaming", specs: ["Alto desempenho", "AM5", "B650E"] },
      { name: "Gigabyte B850 Aorus Elite WiFi", specs: ["Intermediária", "AM5", "B850"] },
      { name: "MSI PRO B650-S WiFi", specs: ["Custo-benefício", "AM5"] },
      { name: "ASRock B760M PG Lightning WiFi", specs: ["Custo-benefício", "LGA1700"] },
    ],
  },
  {
    id: "psu",
    label: "Fontes",
    icon: "🔌",
    items: [
      { name: "Corsair HX1200i", specs: ["Topo de linha", "1200W", "80+ Platinum"] },
      { name: "Corsair RM1000x", specs: ["Alto desempenho", "1000W", "80+ Gold"] },
      { name: "Seasonic Focus GX-850", specs: ["Alto desempenho", "850W", "80+ Gold"] },
      { name: "Corsair RM750e", specs: ["Intermediária", "750W", "80+ Gold"] },
      { name: "MSI MAG A750GL", specs: ["Intermediária", "750W", "80+ Gold"] },
      { name: "Corsair CX650", specs: ["Custo-benefício", "650W", "80+ Bronze"] },
      { name: "XPG Pylon 650W", specs: ["Custo-benefício", "650W", "80+ Bronze"] },
      { name: "Gamemax GP-550", specs: ["Entrada", "550W", "80+ Bronze"] },
      { name: "Corsair CV550", specs: ["Entrada", "550W", "80+ Bronze"] },
      { name: "PCYes Electro V2 500W", specs: ["Básica", "500W"] },
      { name: "Corsair HX1000", specs: ["Topo de linha", "1000W", "80+ Platinum"] },
      { name: "MSI MAG A850GL", specs: ["Alto desempenho", "850W", "80+ Gold"] },
      { name: "Corsair RM850e", specs: ["Alto desempenho", "850W", "80+ Gold"] },
      { name: "Seasonic Focus GX-750", specs: ["Intermediária", "750W", "80+ Gold"] },
      { name: "Corsair RM650e", specs: ["Intermediária", "650W", "80+ Gold"] },
      { name: "XPG Pylon 550W", specs: ["Entrada", "550W", "80+ Bronze"] },
    ],
  },
  {
    id: "monitor",
    label: "Monitores",
    icon: "🖥️",
    items: [
      { name: "Samsung Odyssey OLED G9 49\"", specs: ["Topo de linha", "240Hz", "OLED ultrawide"] },
      { name: "LG UltraGear 27GR95QE OLED", specs: ["Topo de linha", "240Hz", "OLED QHD"] },
      { name: "Dell Alienware AW3423DWF", specs: ["Alto desempenho", "QD-OLED", "ultrawide"] },
      { name: "ASUS ROG Swift PG27AQDM", specs: ["Alto desempenho", "240Hz", "OLED"] },
      { name: "LG UltraGear 27GP850", specs: ["Alto desempenho", "QHD", "165Hz IPS"] },
      { name: "Samsung Odyssey G7 27\"", specs: ["Alto desempenho", "QHD", "240Hz"] },
      { name: "Gigabyte M27Q", specs: ["Intermediária", "QHD", "170Hz"] },
      { name: "LG 24GN65R", specs: ["Intermediária", "Full HD", "144Hz"] },
      { name: "AOC 24G2 24\"", specs: ["Custo-benefício", "Full HD", "144Hz IPS"] },
      { name: "Samsung T350 24\"", specs: ["Custo-benefício", "Full HD", "75Hz"] },
      { name: "AOC 22B2H 22\"", specs: ["Entrada", "Full HD", "75Hz"] },
      { name: "LG 22MK400H", specs: ["Entrada", "Full HD", "75Hz"] },
      { name: "Samsung Odyssey OLED G6 27\"", specs: ["Topo de linha", "QHD", "360Hz OLED"] },
      { name: "Dell S2721DGF", specs: ["Alto desempenho", "QHD", "165Hz IPS"] },
      { name: "ASUS TUF Gaming VG27AQ", specs: ["Intermediária", "QHD", "165Hz"] },
      { name: "LG UltraGear 27GN650", specs: ["Custo-benefício", "Full HD", "144Hz IPS"] },
      { name: "AOC Gaming 24G4", specs: ["Custo-benefício", "Full HD", "180Hz IPS"] },
    ],
  },
  {
    id: "case",
    label: "Gabinetes",
    icon: "🗄️",
    items: [
      { name: "Lian Li O11 Dynamic EVO", specs: ["Topo de linha", "alto fluxo de ar"] },
      { name: "NZXT H9 Flow", specs: ["Alto desempenho", "vidro temperado"] },
      { name: "Corsair 5000D Airflow", specs: ["Alto desempenho", "ATX"] },
      { name: "Lian Li Lancool 216", specs: ["Intermediária", "bom airflow"] },
      { name: "Cooler Master TD500 Mesh", specs: ["Intermediária", "ATX"] },
      { name: "Corsair 4000D Airflow", specs: ["Intermediária", "ATX"] },
      { name: "Montech Air 903 MAX", specs: ["Custo-benefício", "mesh + fans"] },
      { name: "Cooler Master Q300L", specs: ["Custo-benefício", "micro-ATX"] },
      { name: "Gamemax Vega", specs: ["Custo-benefício", "fans RGB"] },
      { name: "PCYes Samurai", specs: ["Entrada", "com fans"] },
      { name: "NZXT H7 Flow", specs: ["Alto desempenho", "airflow + clean"] },
      { name: "Cooler Master NR200P", specs: ["Alto desempenho", "Mini-ITX"] },
      { name: "Lian Li Lancool 207", specs: ["Intermediária", "bom airflow"] },
      { name: "Montech King 95", specs: ["Intermediária", "dual câmara"] },
    ],
  },
  {
    id: "cooler",
    label: "Coolers / Water Coolers",
    icon: "❄️",
    items: [
      { name: "NZXT Kraken Elite 360", specs: ["Topo de linha", "water cooler 360mm"] },
      { name: "Arctic Liquid Freezer III 360", specs: ["Alto desempenho", "AIO 360mm"] },
      { name: "Corsair iCUE H150i Elite", specs: ["Alto desempenho", "AIO 360mm"] },
      { name: "Noctua NH-D15", specs: ["Alto desempenho", "ar (torre dupla)"] },
      { name: "DeepCool LT520", specs: ["Intermediária", "AIO 240mm"] },
      { name: "DeepCool AK620", specs: ["Intermediária", "ar (torre dupla)"] },
      { name: "Cooler Master Hyper 212", specs: ["Custo-benefício", "ar"] },
      { name: "DeepCool AG400", specs: ["Custo-benefício", "ar"] },
      { name: "Cooler box (incluso)", specs: ["Básica", "vem com a CPU"] },
      { name: "Lian Li Galahad II LCD 360", specs: ["Topo de linha", "AIO 360mm + LCD"] },
      { name: "DeepCool LT720 360mm", specs: ["Alto desempenho", "AIO 360mm"] },
      { name: "Arctic Liquid Freezer III 240", specs: ["Alto desempenho", "AIO 240mm"] },
      { name: "Thermalright Peerless Assassin 120 SE", specs: ["Custo-benefício", "ar (torre dupla)"] },
      { name: "DeepCool AK400", specs: ["Custo-benefício", "ar (torre)"] },
    ],
  },
];
